//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Agent
    {
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string AgentTypeTitle
        {
            get
            {
                return AgentType.Title;
            }
        }
        public int SalesForYesr
        {
            get
            {
                int s = 0;
                foreach (ProductSale p in ProductSale)
                {
                    TimeSpan differentWithoutTime = DateTime.Today.Date - p.SaleDate.Date;
                    if ((int)differentWithoutTime.TotalDays <= 365)
                        s += p.ProductCount;
                }
                return s;
            }
        }
        public decimal Sales
        {
            get
            {
                decimal s = 0;
                foreach (ProductSale p in ProductSale)
                {
                    s += p.Stoimost;
                }
                return s;
            }
        }
        public int Discount
        {
            get
            {
                if (Sales >= 500000)
                    return 25;
                if (Sales >= 150000)
                    return 20;
                if (Sales >= 50000)
                    return 10;
                if (Sales >= 10000)
                    return 5;
                return 0;
            }
        }
        public string FonStayle
        {
            get
            {
                if (Discount >= 25)
                    return "LightGreen";
                else
                    return "White";
            }
        }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string AgentPhotoPath
        {
            get
            {
                if (string.IsNullOrEmpty(Logo))
                    return null;

                // Извлекаем только имя файла (после последнего слеша)
                string fileName = Logo;
                int lastSlash = fileName.LastIndexOfAny(new[] { '\\', '/' });
                if (lastSlash >= 0)
                    fileName = fileName.Substring(lastSlash + 1);

                // Убираем возможные ведущие слеши (на всякий случай)
                fileName = fileName.TrimStart('\\', '/');

                // Строим путь к папке imgs/agents
                string fullPath = Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "Imgs", "agents", fileName);

                // Если файл существует – возвращаем путь, иначе null
                return File.Exists(fullPath) ? fullPath : null;
            }
        }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        public virtual AgentType AgentType { get; set; }
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
